# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs',
        ),
        migrations.AddField(
            model_name='joblist',
            name='user',
            field=models.ManyToManyField(related_name='myJobs', to='HandyHelper.User'),
        ),
    ]
