# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0003_joblist_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='user',
        ),
    ]
