# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0005_joblist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='myJob',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='myJobs', to='HandyHelper.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='HandyHelper.User'),
        ),
    ]
