# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0002_auto_20180525_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='desc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
